// Interventions (介入) — what a scenario's queue holds: the action shapes of
// the model (model/action.ts — partitions, silence, equivocations, delay /
// drop, fork creation, vote designation, omitted inclusion), designated
// manually at slot boundaries or generated by an attack's strategy, plus the
// offline operating state (オフライン), which only a manual intervention
// designates.
//
// Interventions are pure data (persistable as part of a scenario) and are
// compiled into the two axes the engine already accepts: a Delivery rule
// (who sees what by when) and per-slot protocol directives (who acts, and
// whether they equivocate). The engine itself is untouched.

import type {
  Action,
  DelayAction,
  DropAction,
  OmitInclusionAction,
  PartitionAction,
  ProposeParentAction,
  StopAction,
} from "../model/action";
import type { SimulationConfig } from "../model/config";
import type { Omission } from "../model/inclusion";
import type { Delivery } from "./localView";
import { coversMessage } from "../model/messageRef";
import type { VoteOverride } from "../model/protocol";
import { proposerForSlot } from "../model/schedule";
import type { SlotDirectives } from "./simulation";
import type { BlockIndex, SlotIndex, ValidatorIndex } from "../model/types";

/** オフライン: the validators neither send (no proposals, no votes) nor
 * receive — their views freeze at the state on entering offline. After
 * returning they catch up through normal propagation only: pent-up messages
 * arrive from the return slot on, never retroactively into the frozen span. */
export interface OfflineIntervention {
  readonly kind: "offline";
  readonly fromSlot: SlotIndex;
  /** Last offline slot (inclusive); absent = until returned. */
  readonly toSlot?: SlotIndex;
  readonly validators: readonly ValidatorIndex[];
}

export type Intervention = Action | OfflineIntervention;

/** The fork count a fork designation may not push past (フォーク上限,
 * 必須 10): current god-view forks + those the pending designations add +
 * this one's own must stay ≤ MAX_FORKS. Forks arising from other
 * interventions are not constrained. */
export const MAX_FORKS = 4;

/** Parents of the fork designations still to execute after `slot`
 * (未実行のフォーク作成指定), in slot order. */
export function pendingForkParents(
  interventions: readonly Intervention[],
  slot: SlotIndex,
): BlockIndex[] {
  return interventions
    .filter(
      (i): i is ProposeParentAction => i.kind === "propose-parent" && i.slot > slot,
    )
    .sort((a, b) => a.slot - b.slot)
    .map((i) => i.parent);
}

/** The interventions that live as a slot span (fromSlot..toSlot). */
export type SpanIntervention = PartitionAction | StopAction | OfflineIntervention;

/**
 * End a span at `cursor` (inclusive) so it no longer covers cursor + 1.
 * A span that has not taken effect yet (fromSlot > cursor) cannot be closed
 * — closing it would produce a toSlot-before-fromSlot event — so the caller
 * must remove the entry instead, signalled by `undefined`.
 */
export function closeSpanAt<I extends SpanIntervention>(
  span: I,
  cursor: SlotIndex,
): I | undefined {
  return span.fromSlot > cursor ? undefined : { ...span, toSlot: cursor };
}

/** Whether a span (fromSlot..toSlot, open when toSlot is absent) covers `slot`. */
export const spanCovers = (
  fromSlot: SlotIndex,
  toSlot: SlotIndex | undefined,
  slot: SlotIndex,
): boolean => slot >= fromSlot && (toSlot === undefined || slot <= toSlot);

/** 稼働状態: online-and-acting, silenced, or fully cut off. */
export type OperatingState = "active" | "stopped" | "offline";

/** A validator's operating state at `slot` under the scheduled spans.
 * Offline wins over stopped when both spans cover the slot. */
export function operatingStateAt(
  interventions: readonly Intervention[],
  validator: ValidatorIndex,
  slot: SlotIndex,
): OperatingState {
  const covers = (kind: "stop" | "offline"): boolean =>
    interventions.some(
      (i) =>
        i.kind === kind &&
        i.validators.includes(validator) &&
        spanCovers(i.fromSlot, i.toSlot, slot),
    );
  return covers("offline") ? "offline" : covers("stop") ? "stopped" : "active";
}

/** Group id of `v` under `groups`; unlisted validators share group -1. */
function groupOf(
  groups: readonly (readonly ValidatorIndex[])[],
  v: ValidatorIndex,
): number {
  for (let i = 0; i < groups.length; i++) {
    if (groups[i]?.includes(v)) return i;
  }
  return -1;
}

const targets = (
  observers: readonly ValidatorIndex[] | undefined,
  observer: ValidatorIndex,
): boolean => observers === undefined || observers.includes(observer);

/**
 * Compile the interventions into one Delivery rule.
 *
 * Monotone pointwise delivery: a message published at p reaches an observer
 * at slot s iff some slot u in [p, s] let it through — every matching delay
 * had expired, sender and observer were unpartitioned, and the observer was
 * online — and it stays arrived (once seen, always seen). So messages
 * published before a partition or an offline span are already through, an
 * offline validator's view freezes (nothing arrives while it is offline),
 * and healing a partition or returning from offline releases everything
 * held back through normal propagation at that slot, never retroactively.
 */
export function compileDelivery(
  interventions: readonly Intervention[],
): Delivery {
  const partitions = interventions.filter(
    (i): i is PartitionAction => i.kind === "partition",
  );
  const offlines = interventions.filter(
    (i): i is OfflineIntervention => i.kind === "offline",
  );
  const delays = interventions.filter((i): i is DelayAction => i.kind === "delay");
  const drops = interventions.filter((i): i is DropAction => i.kind === "drop");

  return (sender, publishedAt, observer, atSlot, message) => {
    if (publishedAt > atSlot) return false;
    if (observer === sender) return true;

    for (const drop of drops) {
      if (
        coversMessage(drop.message, message, sender, publishedAt) &&
        targets(drop.observers, observer)
      ) {
        return false;
      }
    }

    if (
      partitions.length === 0 &&
      offlines.length === 0 &&
      delays.length === 0
    ) {
      return true;
    }
    const deliverableAt = (u: SlotIndex): boolean =>
      delays.every(
        (d) =>
          !(
            coversMessage(d.message, message, sender, publishedAt) &&
            targets(d.observers, observer)
          ) || u >= d.untilSlot,
      ) &&
      !partitions.some(
        (p) =>
          spanCovers(p.fromSlot, p.toSlot, u) &&
          groupOf(p.groups, sender) !== groupOf(p.groups, observer),
      ) &&
      !offlines.some(
        (o) =>
          spanCovers(o.fromSlot, o.toSlot, u) && o.validators.includes(observer),
      );
    for (let u = publishedAt; u <= atSlot; u++) {
      if (deliverableAt(u)) return true;
    }
    return false;
  };
}

/** The protocol directives one slot inherits from the interventions. Stopped
 * and offline validators are equally silent this slot (the difference —
 * whether they still receive — lives on the Delivery axis), so both silence
 * a validator's equivocations too. */
export function directivesForSlot(
  interventions: readonly Intervention[],
  slot: SlotIndex,
  config: SimulationConfig,
): SlotDirectives {
  const stopped = new Set<ValidatorIndex>();
  for (const i of interventions) {
    if (
      (i.kind === "stop" || i.kind === "offline") &&
      spanCovers(i.fromSlot, i.toSlot, slot)
    ) {
      for (const v of i.validators) stopped.add(v);
    }
  }
  const proposer = proposerForSlot(slot, config);
  const doublePropose = interventions.some(
    (i) =>
      i.kind === "double-propose" &&
      i.slot === slot &&
      i.validator === proposer &&
      !stopped.has(proposer),
  );
  const doubleVote = new Map<ValidatorIndex, BlockIndex | undefined>();
  for (const i of interventions) {
    if (i.kind === "double-vote" && i.slot === slot && !stopped.has(i.validator)) {
      doubleVote.set(i.validator, i.head ?? doubleVote.get(i.validator));
    }
  }
  let proposeParent: BlockIndex | undefined;
  for (const i of interventions) {
    if (i.kind === "propose-parent" && i.slot === slot && !stopped.has(proposer)) {
      proposeParent = i.parent;
    }
  }
  const omitted = interventions.filter(
    (i): i is OmitInclusionAction =>
      i.kind === "omit-inclusion" && i.slot === slot && !stopped.has(proposer),
  );
  const omit: Omission | undefined =
    omitted.length === 0
      ? undefined
      : {
          votes: omitted.flatMap((i) => i.votes ?? []),
          evidence: omitted.flatMap((i) => i.evidence ?? []),
        };
  const voteOverrides = new Map<ValidatorIndex, VoteOverride>();
  for (const i of interventions) {
    if (i.kind === "vote-target" && i.slot === slot && !stopped.has(i.validator)) {
      voteOverrides.set(i.validator, {
        ...voteOverrides.get(i.validator),
        ...(i.head !== undefined ? { head: i.head } : {}),
        ...(i.source !== undefined ? { source: i.source } : {}),
        ...(i.target !== undefined ? { target: i.target } : {}),
      });
    }
  }
  return {
    stopped,
    doublePropose,
    doubleVote,
    ...(proposeParent !== undefined ? { proposeParent } : {}),
    ...(omit !== undefined ? { omit } : {}),
    ...(voteOverrides.size > 0 ? { voteOverrides } : {}),
  };
}
