// Scenario (de)serialization — the persistable form of a run's identity:
// initial conditions, the manual interventions and at most one attack (by
// id, attacker set and parameters). A serialized scenario carries a format
// tag and version so future additive fields stay loadable; parsing validates
// everything (tagged union kinds, integer fields, validator ranges) and
// throws on anything unknown, so a loaded scenario is exactly as trustworthy
// as a built one. Pure data in, pure data out: no DOM, no storage — I/O
// belongs to the UI layer.

import type { SplitDelivery } from "../model/action";
import type { Attack, AttackParams } from "../model/attack";
import { equalStakes, type InitialConditions } from "../model/initialConditions";
import type { EvidenceRef } from "../model/inclusion";
import type { Intervention } from "./intervention";
import type { MessageRef } from "../model/messageRef";
import type { AttackInstance } from "./attackRun";
import {
  DEFAULT_PARAMS,
  type CheckpointSwitch,
  type CommitteeAssignment,
  type ForkChoiceRule,
  type ProtocolParams,
} from "../model/protocolParams";
import type { Scenario } from "./scenario";
import { START_SLOT, type Checkpoint, type Vote } from "../model/types";
import {
  MAX_VALIDATOR_COUNT,
  MIN_VALIDATOR_COUNT,
} from "./validatorSet";

export const SCENARIO_FORMAT = "consensus-sim.scenario";
/** Bumped with every change of the saved shape (2: message references by
 * sender / slot / kind, double-vote splits). */
export const SCENARIO_VERSION = 2;

/** A saved run: the scenario plus how far it had advanced. */
export interface SavedRun {
  readonly scenario: Scenario;
  readonly runSlot: number;
}

/** The attack instance as saved: the library id, the attacker set and the
 * parameters — the strategy itself is code, resolved by id on load, and the
 * generated actions are regenerated by the run, never stored. */
export interface SerializedAttack {
  readonly id: string;
  readonly attackers: readonly number[];
  readonly params: AttackParams;
}

export interface SerializedScenario {
  readonly format: typeof SCENARIO_FORMAT;
  readonly version: number;
  readonly config: InitialConditions;
  readonly runSlot: number;
  readonly interventions: readonly Intervention[];
  readonly attack?: SerializedAttack;
}

export function serializeScenario(
  scenario: Scenario,
  runSlot: number,
): SerializedScenario {
  const { attack } = scenario;
  return {
    format: SCENARIO_FORMAT,
    version: SCENARIO_VERSION,
    config: scenario.config,
    runSlot,
    interventions: scenario.interventions,
    ...(attack === undefined
      ? {}
      : {
          attack: { id: attack.id, attackers: attack.attackers, params: attack.params },
        }),
  };
}

/** How saved attacks are resolved: the library, keyed by attack id. */
export type AttackRegistry = ReadonlyMap<string, Attack>;

class ParseError extends Error {}

const isRecord = (x: unknown): x is Record<string, unknown> =>
  typeof x === "object" && x !== null && !Array.isArray(x);

function integer(x: unknown, what: string): number {
  if (typeof x !== "number" || !Number.isInteger(x)) {
    throw new ParseError(`${what} must be an integer`);
  }
  return x;
}

function slotOf(x: unknown, what: string): number {
  const n = integer(x, what);
  if (n < START_SLOT) throw new ParseError(`${what} must be ≥ ${START_SLOT}`);
  return n;
}

function validatorOf(
  x: unknown,
  validatorCount: number,
  what: string,
): number {
  const n = integer(x, what);
  if (n < 0 || n >= validatorCount) {
    throw new ParseError(`${what} must be in [0, ${validatorCount - 1}]`);
  }
  return n;
}

function validatorsOf(
  x: unknown,
  validatorCount: number,
  what: string,
): number[] {
  if (!Array.isArray(x) || x.length === 0) {
    throw new ParseError(`${what} must be a non-empty array`);
  }
  return x.map((v, i) => validatorOf(v, validatorCount, `${what}[${i}]`));
}

function spanOf(
  raw: Record<string, unknown>,
  what: string,
): { fromSlot: number; toSlot?: number } {
  const fromSlot = slotOf(raw.fromSlot, `${what}.fromSlot`);
  if (raw.toSlot === undefined) return { fromSlot };
  const toSlot = slotOf(raw.toSlot, `${what}.toSlot`);
  if (toSlot < fromSlot) {
    throw new ParseError(`${what}.toSlot must be ≥ fromSlot`);
  }
  return { fromSlot, toSlot };
}

function booleanOf(x: unknown, what: string): boolean {
  if (typeof x !== "boolean") throw new ParseError(`${what} must be a boolean`);
  return x;
}

function fractionOf(x: unknown, what: string): number {
  if (typeof x !== "number" || !Number.isFinite(x) || x < 0 || x > 1) {
    throw new ParseError(`${what} must be a number in [0, 1]`);
  }
  return x;
}

function oneOf<T extends string>(
  x: unknown,
  options: readonly T[],
  what: string,
): T {
  if (typeof x !== "string" || !(options as readonly string[]).includes(x)) {
    throw new ParseError(`${what} must be one of ${options.join(" | ")}`);
  }
  return x as T;
}

function committeeOf(
  x: unknown,
  validatorCount: number,
  what: string,
): CommitteeAssignment {
  if (!isRecord(x)) throw new ParseError(`${what} must be an object`);
  if (x.kind === "all") return { kind: "all" };
  if (x.kind === "epoch-split") return { kind: "epoch-split" };
  if (x.kind === "sized") {
    const size = integer(x.size, `${what}.size`);
    if (size < 1 || size > validatorCount) {
      throw new ParseError(`${what}.size must be in [1, ${validatorCount}]`);
    }
    return { kind: "sized", size };
  }
  throw new ParseError(`${what}.kind must be "all", "sized" or "epoch-split"`);
}

const FORK_CHOICE_RULES: readonly ForkChoiceRule[] = ["GHOST", "LMD-GHOST"];
const CHECKPOINT_SWITCHES: readonly CheckpointSwitch[] = [
  "window",
  "unrealized",
  "off",
];

/** Validate protocol parameters; absent means the default preset (merge),
 * so scenarios saved before parameters existed stay loadable. */
function paramsOf(
  x: unknown,
  validatorCount: number,
  what: string,
): ProtocolParams {
  if (x === undefined) return DEFAULT_PARAMS;
  if (!isRecord(x)) throw new ParseError(`${what} must be an object`);
  const leak = x.inactivityLeak;
  if (!isRecord(leak)) {
    throw new ParseError(`${what}.inactivityLeak must be an object`);
  }
  const delayEpochs = integer(leak.delayEpochs, `${what}.inactivityLeak.delayEpochs`);
  if (delayEpochs < 1) {
    throw new ParseError(`${what}.inactivityLeak.delayEpochs must be ≥ 1`);
  }
  return {
    committee: committeeOf(x.committee, validatorCount, `${what}.committee`),
    boost: fractionOf(x.boost, `${what}.boost`),
    forkChoice: oneOf(x.forkChoice, FORK_CHOICE_RULES, `${what}.forkChoice`),
    equivocationDiscount: booleanOf(
      x.equivocationDiscount,
      `${what}.equivocationDiscount`,
    ),
    checkpointSwitch: oneOf(
      x.checkpointSwitch,
      CHECKPOINT_SWITCHES,
      `${what}.checkpointSwitch`,
    ),
    slashing: booleanOf(x.slashing, `${what}.slashing`),
    inactivityLeak: {
      enabled: booleanOf(leak.enabled, `${what}.inactivityLeak.enabled`),
      delayEpochs,
      rate: fractionOf(leak.rate, `${what}.inactivityLeak.rate`),
    },
  };
}

/** Validate initial stakes: one positive integer per validator; absent
 * means equal stakes, so scenarios saved before stakes existed stay
 * loadable. */
function initialStakesOf(
  x: unknown,
  validatorCount: number,
  what: string,
): readonly number[] {
  if (x === undefined) return equalStakes(validatorCount);
  if (!Array.isArray(x) || x.length !== validatorCount) {
    throw new ParseError(`${what} must list one stake per validator`);
  }
  return x.map((s, v) => {
    const stake = integer(s, `${what}[${v}]`);
    if (stake <= 0) throw new ParseError(`${what}[${v}] must be positive`);
    return stake;
  });
}

/** A checkpoint {epoch, block}: two non-negative integers. */
function checkpointOf(x: unknown, what: string): Checkpoint {
  if (!isRecord(x)) throw new ParseError(`${what} must be an object`);
  const epoch = integer(x.epoch, `${what}.epoch`);
  if (epoch < 0) throw new ParseError(`${what}.epoch must be ≥ 0`);
  const block = integer(x.block, `${what}.block`);
  if (block < 0) throw new ParseError(`${what}.block must be ≥ 0`);
  return { epoch, block };
}

function voteOf(x: unknown, validatorCount: number, what: string): Vote {
  if (!isRecord(x)) throw new ParseError(`${what} must be an object`);
  const head = integer(x.head, `${what}.head`);
  if (head < 0) throw new ParseError(`${what}.head must be ≥ 0`);
  return {
    validator: validatorOf(x.validator, validatorCount, `${what}.validator`),
    slot: slotOf(x.slot, `${what}.slot`),
    head,
    source: checkpointOf(x.source, `${what}.source`),
    target: checkpointOf(x.target, `${what}.target`),
  };
}

function messageRefOf(
  x: unknown,
  validatorCount: number,
  what: string,
): MessageRef {
  if (!isRecord(x)) throw new ParseError(`${what} must be an object`);
  const sender = validatorOf(x.sender, validatorCount, `${what}.sender`);
  const slot = slotOf(x.slot, `${what}.slot`);
  if (x.kind === "proposal") {
    if (x.block === undefined) return { kind: "proposal", sender, slot };
    const block = integer(x.block, `${what}.block`);
    if (block <= 0) throw new ParseError(`${what}.block must be positive`);
    return { kind: "proposal", sender, slot, block };
  }
  if (x.kind === "vote") {
    if (x.vote === undefined) return { kind: "vote", sender, slot };
    const vote = voteOf(x.vote, validatorCount, `${what}.vote`);
    if (vote.validator !== sender || vote.slot !== slot) {
      throw new ParseError(`${what}.vote must be the sender's vote of the slot`);
    }
    return { kind: "vote", sender, slot, vote };
  }
  throw new ParseError(`${what}.kind must be "proposal" or "vote"`);
}

function splitOf(
  x: unknown,
  validatorCount: number,
  what: string,
): SplitDelivery {
  if (!isRecord(x)) throw new ParseError(`${what} must be an object`);
  return {
    first: validatorsOf(x.first, validatorCount, `${what}.first`),
    second: validatorsOf(x.second, validatorCount, `${what}.second`),
    untilSlot: slotOf(x.untilSlot, `${what}.untilSlot`),
  };
}

function attackParamsOf(x: unknown, what: string): AttackParams {
  if (!isRecord(x)) throw new ParseError(`${what} must be an object`);
  const params: Record<string, number> = {};
  for (const [name, value] of Object.entries(x)) {
    if (typeof value !== "number" || !Number.isFinite(value)) {
      throw new ParseError(`${what}.${name} must be a finite number`);
    }
    params[name] = value;
  }
  const maxDelay = integer(x.maxDelay, `${what}.maxDelay`);
  if (maxDelay < 0) throw new ParseError(`${what}.maxDelay must be ≥ 0`);
  return { ...params, maxDelay };
}

function attackOf(
  x: unknown,
  validatorCount: number,
  attacks: AttackRegistry,
  what: string,
): AttackInstance {
  if (!isRecord(x)) throw new ParseError(`${what} must be an object`);
  if (typeof x.id !== "string") throw new ParseError(`${what}.id must be a string`);
  const attack = attacks.get(x.id);
  if (attack === undefined) throw new ParseError(`${what}.id is unknown: ${x.id}`);
  const attackers = validatorsOf(x.attackers, validatorCount, `${what}.attackers`);
  if (new Set(attackers).size !== attackers.length) {
    throw new ParseError(`${what}.attackers lists a validator twice`);
  }
  return {
    id: x.id,
    attack,
    attackers,
    params: attackParamsOf(x.params, `${what}.params`),
  };
}

function listOf(x: unknown, what: string): unknown[] {
  if (!Array.isArray(x)) throw new ParseError(`${what} must be an array`);
  return x;
}

const EVIDENCE_KINDS: readonly EvidenceRef["kind"][] = [
  "double-proposal",
  "double-vote",
];

function evidenceRefOf(
  x: unknown,
  validatorCount: number,
  what: string,
): EvidenceRef {
  if (!isRecord(x)) throw new ParseError(`${what} must be an object`);
  return {
    kind: oneOf(x.kind, EVIDENCE_KINDS, `${what}.kind`),
    validator: validatorOf(x.validator, validatorCount, `${what}.validator`),
    slot: slotOf(x.slot, `${what}.slot`),
  };
}

function observersOf(
  raw: Record<string, unknown>,
  validatorCount: number,
  what: string,
): { observers?: readonly number[] } {
  if (raw.observers === undefined) return {};
  return {
    observers: validatorsOf(raw.observers, validatorCount, `${what}.observers`),
  };
}

function interventionOf(
  x: unknown,
  validatorCount: number,
  what: string,
): Intervention {
  if (!isRecord(x)) throw new ParseError(`${what} must be an object`);
  switch (x.kind) {
    case "partition": {
      if (!Array.isArray(x.groups) || x.groups.length === 0) {
        throw new ParseError(`${what}.groups must be a non-empty array`);
      }
      const groups = x.groups.map((g, i) =>
        validatorsOf(g, validatorCount, `${what}.groups[${i}]`),
      );
      const seen = new Set<number>();
      for (const g of groups) {
        for (const v of g) {
          if (seen.has(v)) {
            throw new ParseError(`${what}.groups list V${v} twice`);
          }
          seen.add(v);
        }
      }
      return { kind: "partition", ...spanOf(x, what), groups };
    }
    case "stop":
    case "offline":
      return {
        kind: x.kind,
        ...spanOf(x, what),
        validators: validatorsOf(x.validators, validatorCount, `${what}.validators`),
      };
    case "double-propose":
      return {
        kind: "double-propose",
        slot: slotOf(x.slot, `${what}.slot`),
        validator: validatorOf(x.validator, validatorCount, `${what}.validator`),
      };
    case "double-vote": {
      const head = x.head === undefined ? undefined : integer(x.head, `${what}.head`);
      if (head !== undefined && head < 0) throw new ParseError(`${what}.head must be ≥ 0`);
      const split =
        x.split === undefined ? undefined : splitOf(x.split, validatorCount, `${what}.split`);
      if (split !== undefined && head === undefined) {
        throw new ParseError(`${what}.split requires a designated head`);
      }
      return {
        kind: "double-vote",
        slot: slotOf(x.slot, `${what}.slot`),
        validator: validatorOf(x.validator, validatorCount, `${what}.validator`),
        ...(head === undefined ? {} : { head }),
        ...(split === undefined ? {} : { split }),
      };
    }
    case "delay":
      return {
        kind: "delay",
        message: messageRefOf(x.message, validatorCount, `${what}.message`),
        untilSlot: slotOf(x.untilSlot, `${what}.untilSlot`),
        ...observersOf(x, validatorCount, what),
      };
    case "drop":
      return {
        kind: "drop",
        message: messageRefOf(x.message, validatorCount, `${what}.message`),
        ...observersOf(x, validatorCount, what),
      };
    case "propose-parent": {
      const parent = integer(x.parent, `${what}.parent`);
      if (parent < 0) throw new ParseError(`${what}.parent must be ≥ 0`);
      return { kind: "propose-parent", slot: slotOf(x.slot, `${what}.slot`), parent };
    }
    case "vote-target": {
      const block = (key: "head" | "target") => {
        if (x[key] === undefined) return {};
        const b = integer(x[key], `${what}.${key}`);
        if (b < 0) throw new ParseError(`${what}.${key} must be ≥ 0`);
        return { [key]: b };
      };
      return {
        kind: "vote-target",
        slot: slotOf(x.slot, `${what}.slot`),
        validator: validatorOf(x.validator, validatorCount, `${what}.validator`),
        ...block("head"),
        ...(x.source === undefined ? {} : { source: checkpointOf(x.source, `${what}.source`) }),
        ...block("target"),
      };
    }
    case "omit-inclusion": {
      const votes =
        x.votes === undefined
          ? {}
          : {
              votes: listOf(x.votes, `${what}.votes`).map((v, i) => {
                const ref = messageRefOf(v, validatorCount, `${what}.votes[${i}]`);
                if (ref.kind !== "vote") {
                  throw new ParseError(`${what}.votes[${i}] must be a vote reference`);
                }
                return ref;
              }),
            };
      const evidence =
        x.evidence === undefined
          ? {}
          : {
              evidence: listOf(x.evidence, `${what}.evidence`).map((e, i) =>
                evidenceRefOf(e, validatorCount, `${what}.evidence[${i}]`),
              ),
            };
      return {
        kind: "omit-inclusion",
        slot: slotOf(x.slot, `${what}.slot`),
        ...votes,
        ...evidence,
      };
    }
    default:
      throw new ParseError(`${what}.kind is unknown: ${String(x.kind)}`);
  }
}

/**
 * Parse and validate a serialized scenario (an already-JSON.parsed value).
 * Throws an Error with a specific message on any structural violation. A
 * saved attack is resolved through `attacks`; an id it does not know is a
 * violation.
 */
export function parseScenario(
  data: unknown,
  attacks: AttackRegistry = new Map(),
): SavedRun {
  if (!isRecord(data)) throw new ParseError("scenario must be an object");
  if (data.format !== SCENARIO_FORMAT) {
    throw new ParseError(`format must be "${SCENARIO_FORMAT}"`);
  }
  if (data.version !== SCENARIO_VERSION) {
    throw new ParseError(`unsupported version: ${String(data.version)}`);
  }
  if (!isRecord(data.config)) throw new ParseError("config must be an object");
  const validatorCount = integer(
    data.config.validatorCount,
    "config.validatorCount",
  );
  if (
    validatorCount < MIN_VALIDATOR_COUNT ||
    validatorCount > MAX_VALIDATOR_COUNT
  ) {
    throw new ParseError(
      `config.validatorCount must be in [${MIN_VALIDATOR_COUNT}, ${MAX_VALIDATOR_COUNT}]`,
    );
  }
  const seed = integer(data.config.seed, "config.seed");
  const params = paramsOf(data.config.params, validatorCount, "config.params");
  const initialStakes = initialStakesOf(
    data.config.initialStakes,
    validatorCount,
    "config.initialStakes",
  );
  const runSlot = slotOf(data.runSlot, "runSlot");
  if (!Array.isArray(data.interventions)) {
    throw new ParseError("interventions must be an array");
  }
  const interventions = data.interventions.map((x, i) =>
    interventionOf(x, validatorCount, `interventions[${i}]`),
  );
  const attack =
    data.attack === undefined
      ? {}
      : { attack: attackOf(data.attack, validatorCount, attacks, "attack") };
  return {
    scenario: {
      config: { validatorCount, seed, params, initialStakes },
      interventions,
      ...attack,
    },
    runSlot,
  };
}
